using OpenDeepWiki.Services.Workspaces;
using Xunit;

namespace OpenDeepWiki.Tests.Services.Workspaces;

/// <summary>
/// LocalDocsWriter 单元测试：验证目录自动创建、内容写入、相对路径越界保护。
/// </summary>
public class LocalDocsWriterTests
{
    [Fact]
    public async Task WritePageAsync_RelativePath_CreatesDirectoriesAndWritesContent()
    {
        // arrange
        var root = CreateTempRoot();
        try
        {
            var writer = new LocalDocsWriter(root);
            const string markdown = "# ConfigManager\n\nGenerated by OpenDeepWiki test.\n";
            const string relative = "en/.auto/unity/config/configmanager.md";

            // act
            await writer.WritePageAsync(relative, markdown);

            // assert
            var full = Path.Combine(root, relative);
            Assert.True(File.Exists(full), $"file should exist at {full}");
            var read = await File.ReadAllTextAsync(full);
            Assert.Equal(markdown, read);
        }
        finally
        {
            Cleanup(root);
        }
    }

    [Fact]
    public async Task WriteCatalogAsync_WritesToExactPath()
    {
        var root = CreateTempRoot();
        try
        {
            var writer = new LocalDocsWriter(root);
            const string json = "{\"title\":\"config\"}";
            const string relative = "en/.auto/_meta.json";

            await writer.WriteCatalogAsync(relative, json);

            var full = Path.Combine(root, relative);
            Assert.True(File.Exists(full));
            Assert.Equal(json, await File.ReadAllTextAsync(full));
        }
        finally
        {
            Cleanup(root);
        }
    }

    [Fact]
    public async Task WritePageAsync_PathTraversal_Throws()
    {
        var root = CreateTempRoot();
        try
        {
            var writer = new LocalDocsWriter(root);

            // 相对路径用 ../ 跳出根
            await Assert.ThrowsAsync<InvalidOperationException>(() =>
                writer.WritePageAsync("../../escape.md", "should fail"));
        }
        finally
        {
            Cleanup(root);
        }
    }

    [Fact]
    public async Task WritePageAsync_OverwritesExistingFile()
    {
        var root = CreateTempRoot();
        try
        {
            var writer = new LocalDocsWriter(root);
            const string relative = "en/.auto/_test.md";

            await writer.WritePageAsync(relative, "first");
            await writer.WritePageAsync(relative, "second");

            var read = await File.ReadAllTextAsync(Path.Combine(root, relative));
            Assert.Equal("second", read);
        }
        finally
        {
            Cleanup(root);
        }
    }

    [Fact]
    public async Task CommitAsync_IsNoOp()
    {
        var writer = new LocalDocsWriter(CreateTempRoot());
        // LocalDocsWriter.CommitAsync 应直接完成，不抛异常
        await writer.CommitAsync();
    }

    [Fact]
    public void Constructor_NullOrWhitespaceRoot_Throws()
    {
        Assert.Throws<ArgumentException>(() => new LocalDocsWriter(""));
        Assert.Throws<ArgumentException>(() => new LocalDocsWriter("   "));
    }

    private static string CreateTempRoot()
    {
        var path = Path.Combine(Path.GetTempPath(), $"odw_docs_test_{Guid.NewGuid():N}");
        Directory.CreateDirectory(path);
        return path;
    }

    private static void Cleanup(string path)
    {
        try { Directory.Delete(path, recursive: true); } catch { /* best-effort */ }
    }
}
