using System.Reflection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using OpenDeepWiki.Services.Workspaces;
using OpenDeepWiki.Tests.Chat.Sessions;
using Xunit;

namespace OpenDeepWiki.Tests.Services.Workspaces;

public class RspressDocsExporterIndexTests
{
    [Fact]
    public void ShouldPreserveExistingIndex_OtherRepoFrontmatter_True_SameRepo_False()
    {
        var path = WriteTempIndex(
            "---\n" +
            "title: \"概述\"\n" +
            "order: 0\n" +
            "autoGenerated:\n" +
            "  source:\n" +
            "    repo: GameFrameX.Server.Source\n" +
            "    generator: OpenDeepWiki\n" +
            "---\n# 概述\n");
        try
        {
            Assert.True(InvokeShouldPreserve(CreateExporter(), path, "GameFrameX.Server"));
            Assert.False(InvokeShouldPreserve(CreateExporter(), path, "GameFrameX.Server.Source"));
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Theory]
    [InlineData("no frontmarker at all")]
    [InlineData("---\ntitle: \"手写页\"\n---\n# 内容\n")]
    public void ShouldPreserveExistingIndex_NoProvenance_False(string content)
    {
        var path = WriteTempIndex(content);
        try
        {
            Assert.False(InvokeShouldPreserve(CreateExporter(), path, "GameFrameX.Server"));
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void ShouldPreserveExistingIndex_MissingFile_False()
    {
        var exporter = CreateExporter();
        var path = Path.Combine(Path.GetTempPath(), $"absent-{Guid.NewGuid():N}.md");
        Assert.False(InvokeShouldPreserve(exporter, path, "GameFrameX.Server"));
    }

    private static string WriteTempIndex(string content)
    {
        var path = Path.Combine(Path.GetTempPath(), $"idx-{Guid.NewGuid():N}.md");
        File.WriteAllText(path, content);
        return path;
    }

    private static RspressDocsExporter CreateExporter()
    {
        var configuration = new ConfigurationBuilder().Build();
        return new RspressDocsExporter(
            new TestDbContext(new Microsoft.EntityFrameworkCore.DbContextOptions<TestDbContext>()),
            new RspressPathMapper(),
            new RepoRegistryProvider(configuration, NullLogger<RepoRegistryProvider>.Instance),
            configuration,
            NullLogger<RspressDocsExporter>.Instance);
    }

    private static bool InvokeShouldPreserve(RspressDocsExporter exporter, string path, string repoName)
    {
        var method = typeof(RspressDocsExporter).GetMethod(
            "ShouldPreserveExistingIndex", BindingFlags.NonPublic | BindingFlags.Instance);
        Assert.NotNull(method);
        return (bool)method.Invoke(exporter, new object[] { path, repoName })!;
    }
}
